# Generated by Django 4.1 on 2022-08-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
