# Generated by Django 4.1 on 2022-08-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0005_alter_notes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='description',
            new_name='content',
        ),
    ]
